// @flow
const ingredientsFA = {
  'almond': 'بادام',
  'almonds': 'بادام',
  'annatto': 'آناتو',
  'artichoke hearts': 'کنگر فرنگی',
  'asiago cheese': 'پنیر آسیاگو',
  'bacon': 'بیکِن',
  'baking soda': 'جوش‌شیرین',
  'bell peppers': 'فلفل دلمه‌ای',
  'black pepper': 'فلفل سیاه',
  'butter': 'کره',
  'carrot': 'هویج',
  'carrots': 'هویج',
  'cassava flour': 'آرد کاساوا',
  'canola oil': 'روغن کانولا',
  'celery': 'جعفری',
  'celery powder': 'پودر جعفری',
  'cellulose': 'سلولز',
  'citric acid': 'اسید سیتریک',
  'chablis': 'شراب سفید چابلیس',
  'cheddar cheese': 'پنیر چدار',
  'cheese culture': 'مخمر پنیر',
  'cheese cultures': 'مخمر پنیر',
  'chicken breast': 'سینه مرغ',
  'chicken fat': 'دنبه مرغ',
  'chicken stock': 'آب مرغ پخته‌شده',
  'concentrated grape must': 'پوراب عصاره انگور',
  'cooked brown rice': 'برنج قهوه‌ای پخته‌شده',
  'cooked quinoa': 'کینوا پخته‌شده',
  'cream': 'خامه',
  'cultured milk': 'شیر غنی‌شده با اسید لاکتیک',
  'dehydrated garlic': 'سیر خشک‌شده',
  'dehydrated onion': 'پیاز خشک‌شده',
  'dried chicken stock': 'عصاره مرغ خشک‌شده',
  'dried porcini mushrooms': 'قارچ تیره‌سر خشک‌شده',
  'egg': 'تخم‌مرغ',
  'eggs': 'تخم‌مرغ',
  'enzyme': 'آنزیم‌',
  'enzymes': 'آنزیم‌ها',
  'expeller pressed canola oil': 'روغن کانولا اکسپرس',
  'flat iron steak': 'گوشت راسته گاو استیکی',
  'fruit juice': 'آب میوه',
  'garlic': 'سیر',
  'gelatin': 'ژلاتین',
  'greek yogurt': 'ماست یونانی',
  'green beans': 'لوبیا سبز',
  'half and half': 'نصف نصف',
  'honey': 'عسل',
  'lemon juice': 'آب لیموترش',
  'marsala wine reduction': 'شراب مارسالا غلیظ‌شده',
  'milk': 'شیر',
  'mirepoix stock': 'عصاره سبزیجات',
  'mushroom': 'قارچ',
  'mushrooms': 'قارچ',
  'natamycin': 'ناتامایسیسن',
  'natural flavor': 'طعم‌دهنده‌های طبیعی',
  'natural flavoring': 'طعم‌دهنده‌های طبیعی',
  'nutritional yeast': 'مخمر تغذیه‌ای',
  'oat bran': 'سبوس جو دو‌ سر',
  'olive oil': 'روغن زیتون',
  'omelette': 'املت',
  'onion': 'پیاز',
  'onion stock': 'عصاره پیاز',
  'onion stocks': 'عصاره پیاز',
  'oregano': 'مرزنگوش',
  'paprika': 'پاپریکا',
  'parmesan cheese': 'پنیر پارمزان',
  'pork': 'گوشت خوک',
  'pork sausage': 'سوسیس خوک',
  'potatoes': 'سیب‌زمینی',
  'potato starch': 'نشاسته سیب‌زمینی',
  'quinoa': 'کینوا',
  'red wine vinegar': 'سرکه شراب قرمز',
  'rice flour': 'آرد برنج',
  'roasted chicken stock': 'عصاره مرغ کباب‌شده',
  'roasted tomatoes': 'گوجه‌فرنگی کباب‌شده',
  'salt': 'نمک',
  'sea salt': 'نمک دریا',
  'skim milk': 'شیر بدون چربی',
  'shrimp': 'میگو',
  'spaghetti squash': 'اسپاگتی اِسکواش',
  'spices': 'ادویه‌جات',
  'spinach': 'اسفناج',
  'sugar': 'شکر',
  'swiss cheese': 'پنیر سوئیسی',
  'tomatoes': 'گوجه‌فرنگی',
  'tomato': 'گوجه‌فرنگی',
  'turkey': 'بوقلمون',
  'turkey breast': 'سینه بوقلمون',
  'vinegar': 'سرکه',
  'walnuts': 'گردو',
  'water': 'آب',
  'white balsamic vinegar': 'سرکه بالزامیک سفید',
  'white onion': 'پیاز سفید',
  'white rice': 'برنج سفید',
  'white wine': 'شراب سفید',
  'wine vinegar': 'سرکه شراب',
  'xanthan gum': 'صمغ زانتان',
};

export default ingredientsFA;
